### PR TITLE
Outputs for Emails of participants #20

### PR DESCRIPTION
**Pull request by BenVardy**

### CODE REVIEW

**Review by ajdaniel — DISMISSED** [review]
This looks good to me - but I think you should provide some documentation about how to use it, and what to use it for. That can be here or in the README perhaps

**Comment by markvardy** [comment]
Any idea why the changed files show the whole files being replaced, rather than the lines that were added/changed only? Just wondering if it's a line endings thing. It makes the commit misleading.

**Comment by ajdaniel** [comment]
yeah it's definitely a whitespace change; if I disable showing whitespace changes in the git diff tool then the changes are clearer

**Review by ajdaniel — DISMISSED** [review]

**Comment by BenVardy** [comment]
I think git has stopped converting from CRLF to LF which means that its done the commit with CRLF as that's how the file are on my computer.

**Comment by ajdaniel** [comment]
@BenVardy I think you can inform your editor to use specific line endings so I wonder if it's worth just sticking to LF was it?

**Comment by BenVardy** [comment]
vscode it setup to use LF however when I first cloned the git repo git decided to use CRLF. I disabled this to stop it converting between the two when I cloned a repo but by disabling this I think git also stops converting from CRLF to LF on commit.

**Comment by ajdaniel** [comment]
I don't mind merging this in and sticking with this going forward

**Review by markvardy — CHANGES_REQUESTED** [review]
Just tested for event 23 and it works great!

However, if I request a non-existent event number (e.g. 99) then the command succeeds and outputs a blank CSV. Is it possible to check that the requested event number exists and, if not, return a meaningful error message?

**Review by markvardy — APPROVED** [review]

**Pull request merged**
